// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20240317223409_init2")]
    partial class init2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Degree")
                        .HasColumnType("int");

                    b.Property<int>("Hours")
                        .HasColumnType("int");

                    b.Property<int>("MinDegree")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("dept_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("dept_id");

                    b.ToTable("courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Degree = 100,
                            Hours = 30,
                            MinDegree = 60,
                            Name = "HTML",
                            dept_id = 1
                        },
                        new
                        {
                            Id = 2,
                            Degree = 100,
                            Hours = 40,
                            MinDegree = 60,
                            Name = "CSS",
                            dept_id = 2
                        },
                        new
                        {
                            Id = 3,
                            Degree = 100,
                            Hours = 35,
                            MinDegree = 60,
                            Name = "JS",
                            dept_id = 1
                        },
                        new
                        {
                            Id = 4,
                            Degree = 100,
                            Hours = 20,
                            MinDegree = 60,
                            Name = "ES6",
                            dept_id = 2
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.CrsResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Degree")
                        .HasColumnType("int");

                    b.Property<int>("Trainee_id")
                        .HasColumnType("int");

                    b.Property<int>("crs_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Trainee_id");

                    b.HasIndex("crs_id");

                    b.ToTable("crsResults");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Degree = 95,
                            Trainee_id = 1,
                            crs_id = 1
                        },
                        new
                        {
                            Id = 2,
                            Degree = 90,
                            Trainee_id = 2,
                            crs_id = 2
                        },
                        new
                        {
                            Id = 3,
                            Degree = 80,
                            Trainee_id = 3,
                            crs_id = 3
                        },
                        new
                        {
                            Id = 4,
                            Degree = 70,
                            Trainee_id = 4,
                            crs_id = 4
                        },
                        new
                        {
                            Id = 5,
                            Degree = 50,
                            Trainee_id = 1,
                            crs_id = 2
                        },
                        new
                        {
                            Id = 6,
                            Degree = 85,
                            Trainee_id = 3,
                            crs_id = 2
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Manager")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Manager = "Eng.AhmedMamdouh",
                            Name = "PWD"
                        },
                        new
                        {
                            Id = 2,
                            Manager = "Eng.Christen",
                            Name = "OS"
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Crs_id")
                        .HasColumnType("int");

                    b.Property<string>("ImgURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.Property<int>("dept_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Crs_id");

                    b.HasIndex("dept_id");

                    b.ToTable("Instructors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Alex",
                            Crs_id = 1,
                            ImgURL = "m.jpeg",
                            Name = "mohamed",
                            Salary = 5000,
                            dept_id = 1
                        },
                        new
                        {
                            Id = 2,
                            Address = "Assiut",
                            Crs_id = 2,
                            ImgURL = "m.jpeg",
                            Name = "Ahmed",
                            Salary = 6000,
                            dept_id = 2
                        },
                        new
                        {
                            Id = 3,
                            Address = "Asswan",
                            Crs_id = 3,
                            ImgURL = "f.jpeg",
                            Name = "mai",
                            Salary = 7000,
                            dept_id = 1
                        },
                        new
                        {
                            Id = 4,
                            Address = "Sohag",
                            Crs_id = 4,
                            ImgURL = "f.jpeg",
                            Name = "aya",
                            Salary = 9000,
                            dept_id = 2
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Trainee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("dept_id")
                        .HasColumnType("int");

                    b.Property<int>("grade")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("dept_id");

                    b.ToTable("trainees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Assiut",
                            ImgURL = "F.jpeg",
                            Name = "Manar",
                            dept_id = 1,
                            grade = 1
                        },
                        new
                        {
                            Id = 2,
                            Address = "Assiut",
                            ImgURL = "F.jpeg",
                            Name = "Asmaa",
                            dept_id = 1,
                            grade = 1
                        },
                        new
                        {
                            Id = 3,
                            Address = "Assiut",
                            ImgURL = "F.jpeg",
                            Name = "Zahraa",
                            dept_id = 2,
                            grade = 1
                        },
                        new
                        {
                            Id = 4,
                            Address = "Assiut",
                            ImgURL = "F.jpeg",
                            Name = "Fatma",
                            dept_id = 2,
                            grade = 1
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Course", b =>
                {
                    b.HasOne("WebApplication1.Models.Department", "department")
                        .WithMany("Courses")
                        .HasForeignKey("dept_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("department");
                });

            modelBuilder.Entity("WebApplication1.Models.CrsResult", b =>
                {
                    b.HasOne("WebApplication1.Models.Trainee", "Trainee")
                        .WithMany("Crs")
                        .HasForeignKey("Trainee_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.Course", "course")
                        .WithMany("Crs")
                        .HasForeignKey("crs_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trainee");

                    b.Navigation("course");
                });

            modelBuilder.Entity("WebApplication1.Models.Instructor", b =>
                {
                    b.HasOne("WebApplication1.Models.Course", "Course")
                        .WithMany("Instructors")
                        .HasForeignKey("Crs_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.Department", "department")
                        .WithMany("Instructors")
                        .HasForeignKey("dept_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("department");
                });

            modelBuilder.Entity("WebApplication1.Models.Trainee", b =>
                {
                    b.HasOne("WebApplication1.Models.Department", "department")
                        .WithMany("Trainees")
                        .HasForeignKey("dept_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("department");
                });

            modelBuilder.Entity("WebApplication1.Models.Course", b =>
                {
                    b.Navigation("Crs");

                    b.Navigation("Instructors");
                });

            modelBuilder.Entity("WebApplication1.Models.Department", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Instructors");

                    b.Navigation("Trainees");
                });

            modelBuilder.Entity("WebApplication1.Models.Trainee", b =>
                {
                    b.Navigation("Crs");
                });
#pragma warning restore 612, 618
        }
    }
}
